### ISSUE TITLE
Yay first issue

### ISSUE THREAD

**Issue by Gunner76th** [IHOC/Website#1]
Not an issue with the site, but Acesaver should introduce his new girlfriend to the community and get her into playing Minecraft. :P Love ya and congrats.

**Comment by acesaver** [comment]
Lol. I don't think she is the Minecraft type of person. I'll try but I wouldn't hold my breath. She is great though. Had a fantastic four year old, is gorgeous and very intelligent.

**Comment by acesaver** [comment]
That should read has not had
