### ISSUE TITLE
Updated page issues and suggestions

### ISSUE THREAD

**Issue by Gunner76th** [IHOC/Website#2]
http://teamihoc.com/Home/About erm should probably remove the bit about teamspeak since we no longer use it in favor of discord
when using facebook option to login on http://teamihoc.com I get the following error
App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.
This kicks from Twitter option
Server Error in '/' Application.

Runtime Error

Description: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine. 

Details: To enable the details of this specific error message to be viewable on remote machines, please create a <customErrors> tag within a "web.config" configuration file located in the root directory of the current web application. This <customErrors> tag should then have its "mode" attribute set to "Off".

<configuration>
    <system.web>
        <customErrors mode="Off"/>
    </system.web>
</configuration>

Notes: The current error page you are seeing can be replaced by a custom error page by modifying the "defaultRedirect" attribute of the application's <customErrors> configuration tag to point to a custom error page URL.

<configuration>
    <system.web>
        <customErrors mode="RemoteOnly" defaultRedirect="mycustompage.htm"/>
    </system.web>
</configuration>
Google+ works though
http://teamihoc.com/ at the bottom where we have TeamIHOC on YouTube, perhaps make that a linked heading that takes you to you teamihoc.com/YouTube which has links to our different members channels.
and for TeamIHOC on Discord, have it be a linked heading also that points to this https://discord.gg/0hQAXZIOgrb5RFRG

**Comment by acesaver** [comment]
Made facebook app account live
Update code to support multiple certificates for twitter login
Updated text on about page

**Comment by acesaver** [comment]
there is your discord link, happy?

**Comment by bluevulpine** [comment]
Will work on youtube page.
