### ISSUE TITLE
Main welcome text needs updating.

### ISSUE THREAD

**Issue by Gunner76th** [IHOC/Website#3]
Welcome to the International House of Creepers.
Anyone wishing to help in our transition over to the new Solder system, please message Gunner76th.

All (18+ only) are welcome to join our community but must first go through the application process. For now, the application process will be recreated on our website at a future date. For now, everyone who wants to apply can create a new account here, fill out all the information on their profile, and then send an Administrator a message.

This message text on the landing page needs updating. I tried to figure out where or how to update it myself, but could not figure it out. 

Updated version should have the following:

Change welcome title to "Welcome to Team International House of Creepers (IHOC)"
Remove the section about Solder
Update the section about the application process
Add information about our group

---

Also we can remove the section to the left of this that says:

Welcome Team IHOC
New Diggs for the Team IHOC Forums.

This is being redundant as we are saying welcome to IHOC twice.

**Comment by acesaver** [comment]
Updated the welcome text with a simpler message.

**Comment by Gunner76th** [comment]
I should have clarified, I was refering to the Forums.teamihoc.com page for the redundancy and simplifiaction request.
